services:
  - type: web
    name: truthscan-fake-news-detector
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python -m spacy download en_core_web_sm
    startCommand: gunicorn app:app -w 1 -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT --timeout 300
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.0"