services:
  - type: web
    name: truthscan-fake-news-detector
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python -c "import nltk; nltk.download('stopwords', quiet=True); nltk.download('wordnet', quiet=True); nltk.download('omw-1.4', quiet=True)"
      python download_data.py
      python train.py
    startCommand: gunicorn app:app -w 2 -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.0"
